### ISSUE TITLE
User Agent Disallowed

### ISSUE THREAD

**Issue by rubberbird** [BirdyF/strava_flutter#13] opened 2019-10-26 05:17 UTC
Google sign in is throwing the "User agent disallowed" error. Any change we can update user agent and webView to support?

**Comment by BirdyF** [comment] 2019-10-26 06:26
Sorry I dont understand your question. Can you explain which function/API you are trying to call?

**Comment by rubberbird** [comment] 2019-11-01 17:08
> Sorry I dont understand your question. Can you explain which function/API you are trying to call?

This is the OAuth authorisation code flow. If you choose social sign in with Google, it fails with user agent disallowed.

**Comment by BirdyF** [comment] 2019-11-01 17:43
OK. I understand. I will do additional tests and will see what I can do.

**Comment by rubberbird** [comment] 2019-11-01 20:01
Thanks. It seems you can just use an allowed user agent string and pass it
into your webview browser.

**Comment by BirdyF** [comment] 2019-11-02 08:58
I pushed a new release (build 35) that seems to work using Google to authenticate.
Need to do additional tests on iOS 13.
Let me know if it is fixing your problem

**Comment by BirdyF** [comment] 2019-11-02 09:59
Sorry I had to revert to previous code (in build 36) because the authentication screen (Strava) is not closing. I need to check carefully what can be done with url_launcher package used on oauth.dart

**Comment by BirdyF** [comment] 2019-11-05 10:57
Hi @rubberbird  I think that it is not currently possible on Android.
After some test I think (not 100% sure) that there is a bug when Strava Auth is called in a browser and not in a WebView. 

When I do tests calling in a browser the Strava Auth, it is working and my app get the answer (token...) BUT  the browser screen does not get close.  So url_launcher (flutter side) is working.

I suspect that it could be a Strava problem because I noticed that the same error (user agent disallowed) can be seen on app like Wahoo.

I will continue to investigate but for the moment I will keep the use of webview in url_launcher (keeping the user agent disallowed)

**Comment by BirdyF** [comment] 2019-11-22 17:53
Hi @rubberbird I have done additional tests. Using the same code I found the same problem doing Spotify authentication: 
- Working well (going back from Auth screen) when using WebView
- Not going back from Auth screen when using local browser

So I suspect the problem is not coming from Strava but more probably from url_launcher.
I will continue to to search for a solution and will update.

**Comment by BirdyF** [comment] 2019-12-01 18:32
Hi @rubberbird, There is hope!
I managed to get it working on Android. Now I need to refactor a bit and check if it is still working on iOS.

**Comment by rubberbird** [comment] 2019-12-01 18:36
Sounds good. Keep me posted. I also noticed something off with token renewal, but I think that might just be my code. Will let you know.

**Comment by BirdyF** [comment] 2019-12-02 14:02
I pushed a new version (1.1.0) fixing this problem. It should work on Android (tested on 8.0 and 9.0) but so far I have not been able to test it on iOS because I can not use iOS13 and I have problems on iOS12 to debug. 
I will try again later.
Let me know if you have problems.

**Closed** 2019-12-03 14:26 UTC
Labels: help wanted
